[package]
name = "diesel_test"
version = "0.1.0"
authors = ["Mike Piccolo <mfpiccolo@gmail.com>"]

[dependencies]
diesel = { git = "https://github.com/sgrif/diesel" }
diesel_codegen = { git = "https://github.com/sgrif/diesel", version = "^0.1.0", default-features = false, features = ["nightly"] }
libc = "0.2"
dotenv = "0.4.0"
nickel = "*"
rustc-serialize = "*"
diesel_model = { path = "../diesel_model", default-features = false, features = ["nightly"] }
