[package]
name = "yaqb_test"
version = "0.1.0"
authors = ["Mike Piccolo <mfpiccolo@gmail.com>"]

[dependencies]
yaqb = { path = "../yaqb/yaqb" }
yaqb_codegen = { git = "https://github.com/sgrif/yaqb" }
libc = "0.2"
dotenv = "0.4.0"
nickel = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
rustc-serialize = "*"
